
networks:
  shared-network:
    driver: bridge

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - shared-network