server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-s

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admins
          uri: lb://localhost:8003
          predicates:
            - Path=/admins/**
        - id: users
          uri: lb://localhost:8002
          predicates:
            - Path=/users/**
        - id: trips
          uri: lb://localhost:8004
          predicates:
            - Path=/trips/**
        - id: scooters
          uri: lb://localhost:8001
          predicates:
            - Path=/scooters/**
        - id: stations
          uri: lb://localhost:8005
          predicates:
            - Path=/stations/**




