server:
port: 8080
spring:
  profiles:
   active: native
  application:
       name: config-service
  cloud:
    config:
       server:
          native:
             search-locations: classpath:/config-data
